// Base de 100 smart contracts - 50 valides et 50 invalides
// Fichier sans accents dans le code pour compatibilite Windows/Node.js

const SMART_CONTRACTS = [
  // Contrats valides
  { id: 'valid_01', title: 'Vesting de tokens equipe', description: 'Tokens bloques 2 ans puis liberes lineairement', code: 'contract TeamVesting {\n  uint256 cliff = 730 days;\n}', isValid: true, explanation: 'Vesting align les interets long terme' },
  { id: 'valid_02', title: 'DAO avec quorum', description: 'Quorum 20% et delai de vote 3 jours', code: 'contract SimpleDAO {\n  uint256 quorum = 20;\n}', isValid: true, explanation: 'Quorum et delai = gouvernance responsable' },
  { id: 'valid_03', title: 'Token ERC20 avec cap', description: 'Supply maximum et burn', code: 'contract CappedToken {\n  uint256 MAX_SUPPLY = 100000000;\n}', isValid: true, explanation: 'Cap protege contre inflation' },
  { id: 'valid_04', title: 'Staking avec cooldown', description: 'Periode attente 7 jours', code: 'contract Staking {\n  uint256 COOLDOWN = 7 days;\n}', isValid: true, explanation: 'Cooldown stabilise le reseau' },
  { id: 'valid_05', title: 'NFT Marketplace royalties', description: '5% au createur original', code: 'contract NFTMarket {\n  uint256 ROYALTY = 5;\n}', isValid: true, explanation: 'Royalties pour createurs' },
  { id: 'valid_06', title: 'Multi-signature 2-of-3', description: '2 signatures sur 3 requises', code: 'contract MultiSig {\n  uint256 REQUIRED = 2;\n}', isValid: true, explanation: 'Multi-sig augmente securite' },
  { id: 'valid_07', title: 'Oracle decentralise', description: 'Agregation de 5 sources', code: 'contract Oracle {\n  address[5] sources;\n}', isValid: true, explanation: 'Sources multiples reduisent manipulation' },
  { id: 'valid_08', title: 'Timelock upgrade', description: 'Delai 48h pour upgrades', code: 'contract Timelock {\n  uint256 DELAY = 48 hours;\n}', isValid: true, explanation: 'Timelock pour transparence' },
  { id: 'valid_09', title: 'Escrow avec arbitre', description: 'Tiers neutre pour litiges', code: 'contract Escrow {\n  address arbitrator;\n}', isValid: true, explanation: 'Arbitre pour resolution conflits' },
  { id: 'valid_10', title: 'Token anti-whale', description: 'Limite 1% supply par TX', code: 'contract AntiWhale {\n  uint256 MAX_TX = 1;\n}', isValid: true, explanation: 'Limite manipulations whales' },
  { id: 'valid_11', title: 'Lending collateralise', description: 'Ratio 150% de collateral', code: 'contract Lending {\n  uint256 RATIO = 150;\n}', isValid: true, explanation: 'Collateral protege preteurs' },
  { id: 'valid_12', title: 'Governance non-transferable', description: 'Token soulbound', code: 'contract Soulbound {\n  function transfer() { revert(); }\n}', isValid: true, explanation: 'Empeche achat de votes' },
  { id: 'valid_13', title: 'AMM protection frontrun', description: 'Slippage max defini', code: 'contract AMM {\n  function swap(uint minOut) {}\n}', isValid: true, explanation: 'Protection contre frontrunning' },
  { id: 'valid_14', title: 'Vesting lineaire 4 ans', description: 'Distribution sur 48 mois', code: 'contract LinearVest {\n  uint256 DURATION = 1460 days;\n}', isValid: true, explanation: 'Vesting predictible' },
  { id: 'valid_15', title: 'Lottery Chainlink VRF', description: 'Alea verifiable', code: 'contract Lottery {\n  using VRFConsumer;\n}', isValid: true, explanation: 'VRF garantit alea' },
  { id: 'valid_16', title: 'Token auto-liquidity', description: '2% tax vers pool', code: 'contract AutoLiq {\n  uint256 TAX = 2;\n}', isValid: true, explanation: 'Auto-alimente liquidite' },
  { id: 'valid_17', title: 'Crowdfund remboursable', description: 'Refund si objectif non atteint', code: 'contract Crowdfund {\n  function refund() {}\n}', isValid: true, explanation: 'Protection contributeurs' },
  { id: 'valid_18', title: 'NFT metadata on-chain', description: 'Metadata permanents', code: 'contract OnChainNFT {\n  mapping(uint => string) meta;\n}', isValid: true, explanation: 'Perennite metadata' },
  { id: 'valid_19', title: 'DEX gas limit', description: 'Limite gas par swap', code: 'contract DEX {\n  uint256 MAX_GAS = 300000;\n}', isValid: true, explanation: 'Protection DOS' },
  { id: 'valid_20', title: 'Bridge multi-validator', description: '5 validateurs requis', code: 'contract Bridge {\n  uint256 REQUIRED = 5;\n}', isValid: true, explanation: 'Validation multiple securise' },
  { id: 'valid_21', title: 'Stablecoin algorithmique', description: 'Rebase automatique', code: 'contract Stable {\n  function rebase() {}\n}', isValid: true, explanation: 'Rebase maintient peg' },
  { id: 'valid_22', title: 'Yield farm lock', description: 'Lock 30 jours minimum', code: 'contract YieldFarm {\n  uint256 LOCK = 30 days;\n}', isValid: true, explanation: 'Lock stabilise pools' },
  { id: 'valid_23', title: 'Insurance pool DAO', description: 'Claims votes par holders', code: 'contract Insurance {\n  function voteClaim(uint id) {}\n}', isValid: true, explanation: 'Gouvernance decentralisee' },
  { id: 'valid_24', title: 'Token avec blacklist', description: 'Blocage adresses malveillantes', code: 'contract Compliance {\n  mapping(address => bool) blacklist;\n}', isValid: true, explanation: 'Conformite reglementaire' },
  { id: 'valid_25', title: 'Auction anglaise', description: 'Prix reserve et duree', code: 'contract Auction {\n  uint256 reservePrice;\n}', isValid: true, explanation: 'Mecanisme transparent' },
  { id: 'valid_26', title: 'Subscription service', description: 'Paiement recurrent', code: 'contract Subscription {\n  uint256 PERIOD = 30 days;\n}', isValid: true, explanation: 'Modele abonnement' },
  { id: 'valid_27', title: 'Charity tracable', description: 'Depenses publiques', code: 'contract Charity {\n  Expense[] public expenses;\n}', isValid: true, explanation: 'Transparence dons' },
  { id: 'valid_28', title: 'Vote pondere temps', description: 'Pouvoir selon duree holding', code: 'contract TimeVote {\n  mapping(address => uint) since;\n}', isValid: true, explanation: 'Favorise long terme' },
  { id: 'valid_29', title: 'DEX circuit breaker', description: 'Pause si volatilite 20%', code: 'contract CircuitBreaker {\n  uint256 MAX_VOL = 20;\n}', isValid: true, explanation: 'Protection crash' },
  { id: 'valid_30', title: 'Prediction market', description: 'Resolution par oracle', code: 'contract Prediction {\n  address oracle;\n}', isValid: true, explanation: 'Resolution objective' },
  { id: 'valid_31', title: 'Fractionalized NFT', description: '10000 parts egales', code: 'contract FractNFT {\n  uint256 SHARES = 10000;\n}', isValid: true, explanation: 'Democratise acces NFT' },
  { id: 'valid_32', title: 'Reflection rewards', description: '1% aux holders', code: 'contract Reflection {\n  uint256 FEE = 1;\n}', isValid: true, explanation: 'Recompense passive' },
  { id: 'valid_33', title: 'Treasury avec budget', description: 'Limite mensuelle', code: 'contract Treasury {\n  uint256 monthlyBudget;\n}', isValid: true, explanation: 'Controle depenses' },
  { id: 'valid_34', title: 'Royalty splitter', description: 'Partage entre createurs', code: 'contract Splitter {\n  address[] creators;\n}', isValid: true, explanation: 'Distribution equitable' },
  { id: 'valid_35', title: 'Liquidity mining boost', description: '2x si lock 90 jours', code: 'contract Boosted {\n  function calcReward() {}\n}', isValid: true, explanation: 'Incite engagement' },
  { id: 'valid_36', title: 'Token pausable', description: 'Pause en cas urgence', code: 'contract Pausable {\n  bool paused;\n}', isValid: true, explanation: 'Securite urgence' },
  { id: 'valid_37', title: 'Quadratic voting', description: 'Cout quadratique', code: 'contract Quadratic {\n  function vote(uint amt) {}\n}', isValid: true, explanation: 'Reduit influence whales' },
  { id: 'valid_38', title: 'NFT upgradeable', description: 'Amelioration par burn', code: 'contract UpgradeNFT {\n  mapping(uint => uint) level;\n}', isValid: true, explanation: 'Gamification NFT' },
  { id: 'valid_39', title: 'Transfer conditionnel', description: 'Base sur oracle', code: 'contract Conditional {\n  address oracle;\n}', isValid: true, explanation: 'Contrats conditionnels' },
  { id: 'valid_40', title: 'Token dividends', description: 'Profits distribues', code: 'contract Dividend {\n  uint256 totalDividends;\n}', isValid: true, explanation: 'Partage valeur' },
  { id: 'valid_41', title: 'Auction hollandaise', description: 'Prix decroissant', code: 'contract Dutch {\n  uint256 decrement;\n}', isValid: true, explanation: 'Decouverte prix' },
  { id: 'valid_42', title: 'Reputation system', description: 'Soulbound reputation', code: 'contract Reputation {\n  mapping(address => uint) rep;\n}', isValid: true, explanation: 'Comportements positifs' },
  { id: 'valid_43', title: 'Token auto-burn', description: '0.5% burn par TX', code: 'contract Deflationary {\n  uint256 BURN = 50;\n}', isValid: true, explanation: 'Mecanisme deflation' },
  { id: 'valid_44', title: 'Fair launch', description: 'Pas de pre-mine', code: 'contract FairLaunch {\n  // Distribution publique\n}', isValid: true, explanation: 'Lancement equitable' },
  { id: 'valid_45', title: 'Streaming payment', description: 'Paiement par seconde', code: 'contract Streaming {\n  mapping(address => uint) rate;\n}', isValid: true, explanation: 'Paiement continu' },
  { id: 'valid_46', title: 'Token whitelist', description: 'Phase early access', code: 'contract Whitelist {\n  mapping(address => bool) list;\n}', isValid: true, explanation: 'Distribution controlee' },
  { id: 'valid_47', title: 'Compound staking', description: 'Interets composes', code: 'contract Compound {\n  uint256 APY = 12;\n}', isValid: true, explanation: 'Recompenses croissantes' },
  { id: 'valid_48', title: 'NFT transfer lock', description: 'Conditions de transfer', code: 'contract LockNFT {\n  mapping(uint => bool) locked;\n}', isValid: true, explanation: 'Controle transfers' },
  { id: 'valid_49', title: 'Dynamic supply', description: 'Ajustement auto', code: 'contract Elastic {\n  function rebase() {}\n}', isValid: true, explanation: 'Maintien stabilite' },
  { id: 'valid_50', title: 'Token buyback', description: 'Rachat et burn', code: 'contract Buyback {\n  function buyback() {}\n}', isValid: true, explanation: 'Pression acheteuse' },

  // Contrats invalides
  { id: 'invalid_01', title: 'Supply illimitee', description: 'Mint infini par owner', code: 'contract Infinite {\n  function mint(uint amt) {}\n}', isValid: false, explanation: 'Dilution sans limite' },
  { id: 'invalid_02', title: 'Lottery timestamp', description: 'Alea via blockhash', code: 'contract Lottery {\n  uint rand = block.timestamp;\n}', isValid: false, explanation: 'Manipulable par mineurs' },
  { id: 'invalid_03', title: 'Token backdoor', description: 'Owner peut voler tokens', code: 'contract Backdoor {\n  function steal() onlyOwner {}\n}', isValid: false, explanation: 'Vol possible par owner' },
  { id: 'invalid_04', title: 'ICO sans vesting', description: '50% equipe immediatement', code: 'contract ICO {\n  // Pas de vesting\n}', isValid: false, explanation: 'Risque rug pull' },
  { id: 'invalid_05', title: 'Cle privee hardcodee', description: 'Secret dans code', code: 'contract Hardcoded {\n  bytes32 KEY = 0x123;\n}', isValid: false, explanation: 'Cle visible publiquement' },
  { id: 'invalid_06', title: 'Ponzi scheme', description: 'Anciens payes par nouveaux', code: 'contract Ponzi {\n  function invest() {}\n}', isValid: false, explanation: 'Modele insoutenable' },
  { id: 'invalid_07', title: 'Reentrancy bug', description: 'Vulnerable reentrancy', code: 'contract Vuln {\n  function withdraw() {}\n}', isValid: false, explanation: 'Peut drainer fonds' },
  { id: 'invalid_08', title: 'Oracle centralise', description: 'Une seule source prix', code: 'contract CentralOracle {\n  address source;\n}', isValid: false, explanation: 'Point unique defaillance' },
  { id: 'invalid_09', title: 'Fee 50% ventes', description: 'Frais excessifs', code: 'contract HighFee {\n  uint256 FEE = 50;\n}', isValid: false, explanation: 'Impossible recuperer investissement' },
  { id: 'invalid_10', title: 'NFT metadata mutable', description: 'Createur peut changer', code: 'contract MutableNFT {\n  function setMeta() {}\n}', isValid: false, explanation: 'Rug pull post-vente' },
  { id: 'invalid_11', title: 'DEX sans slippage', description: 'Pas de protection', code: 'contract UnsafeDEX {\n  function swap(uint amt) {}\n}', isValid: false, explanation: 'Vulnerable frontrunning' },
  { id: 'invalid_12', title: 'Staking sans check', description: 'Stake sans verification', code: 'contract BadStake {\n  function stake(uint amt) {}\n}', isValid: false, explanation: 'Bug stake tokens inexistants' },
  { id: 'invalid_13', title: 'Vote flash loan', description: 'Tokens non lockes', code: 'contract FlashVote {\n  function vote(uint id) {}\n}', isValid: false, explanation: 'Manipulation par flash loan' },
  { id: 'invalid_14', title: 'Crowdfund sans limite', description: 'Pas de deadline', code: 'contract UnlimitedCrowd {\n  function contribute() {}\n}', isValid: false, explanation: 'Risque vol' },
  { id: 'invalid_15', title: 'Pause permanente', description: 'Pas de unpause', code: 'contract PermaPause {\n  function pause() {}\n}', isValid: false, explanation: 'Gel definitif possible' },
  { id: 'invalid_16', title: 'Bridge sans signature', description: 'Pas de validation', code: 'contract UnsafeBridge {\n  function receive(bytes msg) {}\n}', isValid: false, explanation: 'Messages forges possibles' },
  { id: 'invalid_17', title: 'Airdrop gas griefing', description: 'Peut bloquer reseau', code: 'contract Airdrop {\n  function send(address[] to) {}\n}', isValid: false, explanation: 'Pas de limite recipients' },
  { id: 'invalid_18', title: 'Lending sans liquidation', description: 'Prets non-collateralises', code: 'contract UnsafeLend {\n  function borrow(uint amt) {}\n}', isValid: false, explanation: 'Perte pour preteurs' },
  { id: 'invalid_19', title: 'Integer overflow', description: 'Pas de check overflow', code: 'contract Overflow {\n  function transfer(uint amt) {}\n}', isValid: false, explanation: 'Creation tokens par overflow' },
  { id: 'invalid_20', title: 'Marketplace sans escrow', description: 'Paiement avant NFT', code: 'contract NoEscrow {\n  function buy(uint id) {}\n}', isValid: false, explanation: 'Vendeur peut garder tout' },
  { id: 'invalid_21', title: 'Blockhash random', description: 'Alea manipulable', code: 'contract BadRandom {\n  uint r = uint(blockhash(block.number));\n}', isValid: false, explanation: 'Mineurs manipulent' },
  { id: 'invalid_22', title: 'Proxy unsafe', description: 'Upgrade sans timelock', code: 'contract UnsafeProxy {\n  function upgrade(address impl) {}\n}', isValid: false, explanation: 'Vol instantane possible' },
  { id: 'invalid_23', title: 'Blacklist arbitraire', description: 'Exclusion sans raison', code: 'contract Arbitrary {\n  function blacklist(address u) {}\n}', isValid: false, explanation: 'Censure arbitraire' },
  { id: 'invalid_24', title: 'Stablecoin sans reserves', description: 'Pas de backing', code: 'contract Unbacked {\n  function mint(uint amt) {}\n}', isValid: false, explanation: 'Risque depeg total' },
  { id: 'invalid_25', title: 'Yield 10000% APY', description: 'Rendements impossibles', code: 'contract Unsustainable {\n  uint256 APY = 10000;\n}', isValid: false, explanation: 'Ponzi deguise' },
  { id: 'invalid_26', title: 'NFT supply infinie', description: 'Mint sans limite', code: 'contract InfiniteNFT {\n  function mint() {}\n}', isValid: false, explanation: 'Pas de rarete' },
  { id: 'invalid_27', title: 'Oracle last trade', description: 'Prix du dernier swap', code: 'contract ManipOracle {\n  uint256 lastPrice;\n}', isValid: false, explanation: 'Manipulation facile' },
  { id: 'invalid_28', title: 'Tax asymetrique', description: '10% achat 0% vente', code: 'contract AsymTax {\n  // Tax buy only\n}', isValid: false, explanation: 'Encourage dump' },
  { id: 'invalid_29', title: 'DAO sans quorum', description: 'Passe avec 1 vote', code: 'contract NoQuorum {\n  function execute(uint id) {}\n}', isValid: false, explanation: 'Attaque minoritaire' },
  { id: 'invalid_30', title: 'Vesting revocable', description: 'Owner peut annuler', code: 'contract Revocable {\n  function revoke(address u) {}\n}', isValid: false, explanation: 'Pas de garantie' },
  { id: 'invalid_31', title: 'Lottery truquee', description: 'Certains privilegies', code: 'contract Rigged {\n  mapping(address => bool) priv;\n}', isValid: false, explanation: 'Pas equitable' },
  { id: 'invalid_32', title: 'Token non-transferable', description: 'Achete mais pas vendable', code: 'contract NonTransfer {\n  function transfer() { revert(); }\n}', isValid: false, explanation: 'Scam evident' },
  { id: 'invalid_33', title: 'Penalty 100%', description: 'Perte totale si unstake', code: 'contract Predatory {\n  function unstake() {}\n}', isValid: false, explanation: 'Vol deguise' },
  { id: 'invalid_34', title: 'ICO sans soft cap', description: 'Garde fonds meme 100$', code: 'contract NoSoftCap {\n  function end() {}\n}', isValid: false, explanation: 'Pas de protection' },
  { id: 'invalid_35', title: 'Oracle stale', description: 'Update hebdomadaire', code: 'contract Stale {\n  uint256 UPDATE = 7 days;\n}', isValid: false, explanation: 'Prix obsoletes' },
  { id: 'invalid_36', title: 'MultiSig 1-of-10', description: 'Un seul signer suffit', code: 'contract Weak {\n  uint256 THRESHOLD = 1;\n}', isValid: false, explanation: 'Pas de securite' },
  { id: 'invalid_37', title: 'Token selfdestruct', description: 'Destruction possible', code: 'contract SelfDestruct {\n  function destroy() {}\n}', isValid: false, explanation: 'Exit scam' },
  { id: 'invalid_38', title: 'NFT premine cache', description: 'Rares pre-mintes', code: 'contract Premine {\n  // Equipe mint rares\n}', isValid: false, explanation: 'Distribution injuste' },
  { id: 'invalid_39', title: 'Vote double-count', description: 'Voter plusieurs fois', code: 'contract DoubleVote {\n  function vote(uint id) {}\n}', isValid: false, explanation: 'Gouvernance cassee' },
  { id: 'invalid_40', title: 'Referral pyramid', description: 'Schema pyramidal', code: 'contract Pyramid {\n  // 20 niveaux\n}', isValid: false, explanation: 'Illegal' },
  { id: 'invalid_41', title: 'Hidden mint', description: 'Fonction cachee', code: 'contract Hidden {\n  function execute(bytes data) {}\n}', isValid: false, explanation: 'Backdoor mint' },
  { id: 'invalid_42', title: 'Rebase defaillant', description: 'Amplifie volatilite', code: 'contract BrokenRebase {\n  function rebase() {}\n}', isValid: false, explanation: 'Spirale mort' },
  { id: 'invalid_43', title: 'Rug pull DEX', description: 'Retrait liquidite owner', code: 'contract RugDEX {\n  function removeLiq() onlyOwner {}\n}', isValid: false, explanation: 'Rug programme' },
  { id: 'invalid_44', title: 'Auction snipeable', description: 'Fin immediate', code: 'contract Snipe {\n  function bid() {}\n}', isValid: false, explanation: 'Favorise bots' },
  { id: 'invalid_45', title: 'Max wallet variable', description: 'Limite changeable', code: 'contract Moving {\n  function setMax(uint m) {}\n}', isValid: false, explanation: 'Force vente' },
  { id: 'invalid_46', title: 'Presale sans KYC', description: 'Attaque Sybil', code: 'contract NoKYC {\n  function buy() {}\n}', isValid: false, explanation: 'Distribution injuste' },
  { id: 'invalid_47', title: 'Vote selling', description: 'Vente de votes', code: 'contract VoteSell {\n  function sellVote(address to) {}\n}', isValid: false, explanation: 'Corruption gouvernance' },
  { id: 'invalid_48', title: 'Insurance sans capital', description: 'Pool vide', code: 'contract EmptyInsurance {\n  function claim() {}\n}', isValid: false, explanation: 'Promesses impossibles' },
  { id: 'invalid_49', title: 'Router approval drain', description: 'Vol via approval', code: 'contract Malicious {\n  function swap() {}\n}', isValid: false, explanation: 'Vol tous tokens' },
  { id: 'invalid_50', title: 'Tax vers wallet prive', description: '10% au createur', code: 'contract PrivateTax {\n  address taxWallet = 0x123;\n}', isValid: false, explanation: 'Enrichissement createur' }
];

module.exports = { SMART_CONTRACTS };
